# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >- # this means to ignore newlines until "baseurl:"
  Introducción a la resolución de problemas computacionales, 
  que incluye los fundamentos de la programación informática. Los temas 
  incluyen constructos de programación imperativa (variables, bucles, 
  condicionales, funciones, recursión), constructos básicos orientados a objetos 
  (clases, objetos) y algunos algoritmos fundamentales y estructuras de datos 
  (diccionarios, matrices, listas enlazadas). Los estudiantes aprenden estos conceptos 
  a través del estudio del lenguaje de programación Python.

baseurl: "/TemplateCursoComputacional" # the subpath of your site, e.g. /blog
url: "https://juancollante.github.io" # the base hostname & protocol for your site, e.g. http://example.com

number: Introducción al pensamiento computacional
title: Curso introductorio de ciencias computacionales
semester: primer semestre de 2024
hypothesis: false

navigation:
  - title: General
    subfolderitems:
      - page: Descripción
        url: '#description'
      - page: Metas de aprendizaje
        url: '#goals'
      - page: Recursos
        url: '#resources'
  - page: Codigo
    url: '#inclasscode'
  - title: Trabajos
    subfolderitems:
      - page: Tareas y Quices
        url: '#hwqz'
      - page: Laboratorios
        url: '#labs'
      - page: Proyectos
        url: '#projects'
      - page: Examenes
        url: '#exams'
  - page: Compromiso
    url: '#commitments'

instructors:
  - id: Juan
    nombre: Juan Collante
    email: juan.collante@udea.edu.co
    web: 404.html
    telefono: 83482902
    horario de atención: Lu-Vi 2:00 a 3:00 
  - id: XX_YY_ZZ
    nombre: XX_YY_ZZ
    email: XX_YY_ZZ
    web: XX_YY_ZZ
    telefono: 1234560
    horario de atención: 404.html
  - id: XX_YY_ZZ
    nombre: XX_YY_ZZ
    email: XX_YY_ZZ
    web: XX_YY_ZZ
    telefono: 1234560
    horario de atención: 404.html
  - id: XX_YY_ZZ
    nombre: XX_YY_ZZ
    email: XX_YY_ZZ
    web: XX_YY_ZZ
    telefono: 1234560
    horario de atención: 404.html

offerings:
  - name: CLASE 01
    loc: AULA CENTRAL
    time: MWV 8:10am - 9:00am
    instructor: Collante
  - name: CLASE 02
    loc: AULA CENTRAL
    time: MWV 11:10am - 12:00pm
    instructor: goadrich
  - name: LAB 01
    loc: Laboratorio TIC
    time: Ju 1:10pm - 4:00pm
    instructor: ferrer
  - name: LAB 02
    loc: Snoddy Computer Lab
    time: W 1:10pm - 4:00pm
    instructor: seme

resources:
  - name: Python 3
    image: assets/images/pythonlogo.png
    url: http://python.org
  - name: Azure Notebooks
    image: assets/images/azure.png
    url: https://notebooks.azure.com/
  - name: Pycharm
    image: assets/images/pycharmlogo.png
    url: https://www.jetbrains.com/pycharm/

extra-resources:
  - name: "How to Think Like a Computer Scientist: Interactive Edition"
    image: assets/images/runestone_logo.png
    url: https://runestone.academy/runestone/books/published/thinkcspy/index.html
  - name: Python Tutor
    image: assets/images/python_tutor.png
    url: http://pythontutor.com/
  - name: CodingBat Python
    image: assets/images/codingbat.jpg
    url: https://codingbat.com/python
  - name: CheckiO Python Practice
    image: assets/images/checkio_logo_small.png
    url: https://py.checkio.org/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
